//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISPCFG.Msce {
    
    
    public partial class wucHeaderNavBar {
        
        /// <summary>
        /// webmnu_header_options control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1WebMenu webmnu_header_options;
        
        /// <summary>
        /// mnuInicio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem mnuInicio;
        
        /// <summary>
        /// mnu_separator01 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem mnu_separator01;
        
        /// <summary>
        /// mnuMaestria control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem mnuMaestria;
        
        /// <summary>
        /// mnu_separator02 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem mnu_separator02;
        
        /// <summary>
        /// mnuPersonal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem mnuPersonal;
        
        /// <summary>
        /// mnu_separator03 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem mnu_separator03;
        
        /// <summary>
        /// mnuBibliografia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem mnuBibliografia;
        
        /// <summary>
        /// mnu_separator04 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem mnu_separator04;
        
        /// <summary>
        /// mnuConsultas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem mnuConsultas;
        
        /// <summary>
        /// mnu_separator05 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem mnu_separator05;
        
        /// <summary>
        /// mnuEncuentros control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem mnuEncuentros;
        
        /// <summary>
        /// mnu_separator06 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem mnu_separator06;
        
        /// <summary>
        /// mnuMiMaletin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem mnuMiMaletin;
        
        /// <summary>
        /// mnu_separator07 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem mnu_separator07;
        
        /// <summary>
        /// mnuMiproyecto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem mnuMiproyecto;
        
        /// <summary>
        /// C1SubMenuMaestria control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1SubMenu C1SubMenuMaestria;
        
        /// <summary>
        /// smnuDatosGenerales control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuDatosGenerales;
        
        /// <summary>
        /// smnuModulos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuModulos;
        
        /// <summary>
        /// smnuCursosTemas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuCursosTemas;
        
        /// <summary>
        /// smnuMenciones control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuMenciones;
        
        /// <summary>
        /// smnuSedes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuSedes;
        
        /// <summary>
        /// smnuGrupos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuGrupos;
        
        /// <summary>
        /// smnuTemasProyecto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuTemasProyecto;
        
        /// <summary>
        /// C1SubMenuPersonal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1SubMenu C1SubMenuPersonal;
        
        /// <summary>
        /// smnuCategoriasDocentes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuCategoriasDocentes;
        
        /// <summary>
        /// smnuTitulosAcademicos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuTitulosAcademicos;
        
        /// <summary>
        /// smnuAcademicos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuAcademicos;
        
        /// <summary>
        /// smnuDocentes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuDocentes;
        
        /// <summary>
        /// smnuMaestrantes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuMaestrantes;
        
        /// <summary>
        /// C1SubMenuBibliografia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1SubMenu C1SubMenuBibliografia;
        
        /// <summary>
        /// smnuBibliografiaCD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuBibliografiaCD;
        
        /// <summary>
        /// smnuBibliografiaAudiovisual control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuBibliografiaAudiovisual;
        
        /// <summary>
        /// smnuBibliografiaDocumento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuBibliografiaDocumento;
        
        /// <summary>
        /// smnuBuscarBibliografia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuBuscarBibliografia;
        
        /// <summary>
        /// C1SubMenuConsultas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1SubMenu C1SubMenuConsultas;
        
        /// <summary>
        /// smnuConsultar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuConsultar;
        
        /// <summary>
        /// smnuResponderConsultas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuResponderConsultas;
        
        /// <summary>
        /// smnuBuscarConsultas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::C1.Web.C1Command.C1MenuItem smnuBuscarConsultas;
    }
}
